#!/bin/bash
#
# Download the upstream release tarballs the specs need into SOURCES/.
#
# The vendored opentelemetry-cpp tree is NOT fetched here -- it is assembled by
# scripts/vendor-otelcpp.sh, because it needs git submodules that release
# tarballs do not contain.
#
set -euo pipefail

cd "$(dirname "$0")/.."
# shellcheck disable=SC1091
. ./versions.env

OUT="SOURCES"
mkdir -p "$OUT"

fetch() { # url filename
    local url="$1" name="$2"
    if [ -s "$OUT/$name" ]; then
        echo "==> $name already present"
        return 0
    fi
    echo "==> fetching $name"
    curl -fsSL --retry 3 --retry-delay 2 -o "$OUT/$name.part" "$url"
    mv "$OUT/$name.part" "$OUT/$name"
}

# GitHub's per-tag archives are generated by `git archive`, so cloning the tag
# and running git archive ourselves reproduces the same tree with the same
# prefix.  Used as a fallback for environments where codeload is unreachable
# (proxies that allow git but not the archive endpoints) -- the content is
# equivalent, though the tarball is not byte-identical to GitHub's.
fetch_github() { # owner/repo tag filename prefix
    local repo="$1" tag="$2" name="$3" prefix="$4"
    if [ -s "$OUT/$name" ]; then
        echo "==> $name already present"
        return 0
    fi
    echo "==> fetching $name"
    if curl -fsSL --retry 3 --retry-delay 2 -o "$OUT/$name.part" \
            "https://github.com/${repo}/archive/refs/tags/${tag}.tar.gz"; then
        mv "$OUT/$name.part" "$OUT/$name"
        return 0
    fi
    rm -f "$OUT/$name.part"

    echo "    archive endpoint unavailable, reconstructing from the git tag"
    local tmp
    tmp="$(mktemp -d)"
    git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$tag" \
        "https://github.com/${repo}.git" "$tmp/src"
    git -C "$tmp/src" archive --format=tar.gz --prefix="${prefix}/" HEAD \
        > "$OUT/$name.part"
    mv "$OUT/$name.part" "$OUT/$name"
    rm -rf "$tmp"
}

haproxy_branch="${HAPROXY_VERSION%.*}"

fetch "https://www.haproxy.org/download/${haproxy_branch}/src/haproxy-${HAPROXY_VERSION}.tar.gz" \
      "haproxy-${HAPROXY_VERSION}.tar.gz"

fetch_github haproxytech/haproxy-opentelemetry "v${OTEL_FILTER_VERSION}" \
      "haproxy-opentelemetry-${OTEL_FILTER_VERSION}.tar.gz" \
      "haproxy-opentelemetry-${OTEL_FILTER_VERSION}"

fetch_github haproxytech/opentelemetry-c-wrapper "v${OTEL_WRAPPER_VERSION}" \
      "opentelemetry-c-wrapper-${OTEL_WRAPPER_VERSION}.tar.gz" \
      "opentelemetry-c-wrapper-${OTEL_WRAPPER_VERSION}"

echo
echo "==> SOURCES/"
ls -la "$OUT"
